### ISSUE TITLE
6/17 - 6/21: Setup & Planning Ahead

### ISSUE THREAD

**Issue by PaarasPurohit** [Team-Optix-3749/OptixToolkit#15]
# Description

As 6/3 - 6/7 and 6/10 - 6/14 were used for establishing members of the team, this week, 6/17 - 6/21 was used for establishing what works, what doesn't work, what steps are to be taken to ensure completion, and delegation of tasks.

# Tasks Completed

- [x] Established frontend team: **Aarush, Tanav, Aadi**
- [x] Established backend team: **Neel, Paaras**
- [x] Established tasks that need to be completed for both frontend and backend
- [x] Organized tasks in [backlog](https://github.com/users/PaarasPurohit/projects/6/views/1)

# Key Commits

No commits for this week, as it was all about planning and preparation.

# Code & Further Explanations

You can find the tasks for the front end [here](https://github.com/users/PaarasPurohit/projects/6/views/1?pane=issue&itemId=67583664) and the back end [here](https://github.com/users/PaarasPurohit/projects/6/views/1?pane=issue&itemId=67583847).

# Individual Work

- Tanav: Worked with Paaras to establish the plans for the frontend
- Neel: Worked with Paaras to establish the plans for the backend
- Aarush, Aadi: Learned how Toolkit works, as neither of them had any Toolkit-specific experience.
