### ISSUE TITLE
Final Touches on Barcode Scanner - Toolkit for Summer 2024

### ISSUE THREAD

**Issue by PaarasPurohit** [Team-Optix-3749/OptixToolkit#17]
# Tasks Completed

- [x] Took inventory of Build with columns needed
- [x] Combined electrical and build inventory into one sheet
- [x] Updated app database with spreadsheet through Apps Script
- [x] Final touches on admin panel, frontend
- [x] New schema updated to backend
